// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/customers': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/customers').default>>>>
    }
    '/api/mails': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/mails').default>>>>
    }
    '/api/members': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/members').default>>>>
    }
    '/api/notifications': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@4.0.3_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@24.0.3_@vue+compiler-_a80f18eca66715f7b0746c407a09cec0/node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@2.0.0_magicast@0.3.5_vite@7.1.2_@types+node@24.0.3_jiti@2.5.1_lightningcss@1_ec844d4da83de72cb7d60501e03af8e6/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}